package constants

const ENV_NAME = "ENV"
const SERVER_SOCKET_HOST_NAME = "SERVER_SOCKET_HOST"
const SERVER_SOCKET_PORT_NAME = "SERVER_SOCKET_PORT"
const SERVER_SOCKET_TYPE_NAME = "SERVER_SOCKET_TYPE"
const LOGS_NAME = "LOGS"

const BOOLEAN_TRUE_ENV_VALUE = "true"

const DEVELOPMENT_ENV_VALUE = "development"
const DEVELOPMENT_DOCKER_ENV_VALUE = "development-docker"
const PRODUCTION_ENV_VALUE = "production"

const SOCKET_PAYLOAD_OPERATION_TYPE_CREATE = "create"
const SOCKET_PAYLOAD_OPERATION_TYPE_DELETE = "delete"
const SOCKET_PAYLOAD_OPERATION_TYPE_GET = "get"
